/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author Muhammad Ramadhani
 */
public class PilihGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarComboBox
     */
    public PilihGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        pLOTR = new javax.swing.JLabel();
        Pilihan = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JPanel();
        lotr2LB = new javax.swing.JLabel();
        lotr3LB = new javax.swing.JLabel();
        lotr1LB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPanel.add(pLOTR);

        Pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lord of the Rings 1", "Lord of the Rings 2", "Lord of the Rings 3" }));
        Pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihanActionPerformed(evt);
            }
        });
        buttonPanel.add(Pilihan);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.CENTER);

        imagePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagePanel.setLayout(new java.awt.CardLayout());

        lotr2LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotr2LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/lotr2.jpg"))); // NOI18N
        imagePanel.add(lotr2LB, "1");

        lotr3LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotr3LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/lotr3.jpg"))); // NOI18N
        imagePanel.add(lotr3LB, "2");

        lotr1LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotr1LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/lotr1.jpg"))); // NOI18N
        lotr1LB.setToolTipText("");
        lotr1LB.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(lotr1LB, "0");

        getContentPane().add(imagePanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihanActionPerformed
        CardLayout cl  = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel,String.valueOf(Pilihan.getSelectedIndex()));
    }//GEN-LAST:event_PilihanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Pilihan;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lotr1LB;
    private javax.swing.JLabel lotr2LB;
    private javax.swing.JLabel lotr3LB;
    private javax.swing.JLabel pLOTR;
    // End of variables declaration//GEN-END:variables
}
