/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author Muhammad Ramadhani
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButtonFullScreen
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        lotr1BT = new javax.swing.JButton();
        lotr2BT = new javax.swing.JButton();
        lotr3BT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        lotr1LB = new javax.swing.JLabel();
        lotr2LB = new javax.swing.JLabel();
        lotr3LB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lotr1BT.setText("Lord of the Rings 1");
        lotr1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotr1BTActionPerformed(evt);
            }
        });
        buttonPanel.add(lotr1BT);

        lotr2BT.setText("Lord of the Rings 2");
        lotr2BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotr2BTActionPerformed(evt);
            }
        });
        buttonPanel.add(lotr2BT);

        lotr3BT.setText("Lord of the Rings 3");
        lotr3BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotr3BTActionPerformed(evt);
            }
        });
        buttonPanel.add(lotr3BT);

        exitBT.setText("Exit");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lotr1LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotr1LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/lotr1.jpg"))); // NOI18N
        lotr1LB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lotr1LB.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(lotr1LB, "0");

        lotr2LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotr2LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/lotr2.jpg"))); // NOI18N
        lotr2LB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(lotr2LB, "1");

        lotr3LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotr3LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/lotr3.jpg"))); // NOI18N
        lotr3LB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(lotr3LB, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotr1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotr1BTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"0");
    }//GEN-LAST:event_lotr1BTActionPerformed

    private void lotr2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotr2BTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"1");
    }//GEN-LAST:event_lotr2BTActionPerformed

    private void lotr3BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotr3BTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"2");
    }//GEN-LAST:event_lotr3BTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButtonFullScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton lotr1BT;
    private javax.swing.JLabel lotr1LB;
    private javax.swing.JButton lotr2BT;
    private javax.swing.JLabel lotr2LB;
    private javax.swing.JButton lotr3BT;
    private javax.swing.JLabel lotr3LB;
    // End of variables declaration//GEN-END:variables
}
